services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    tty: true
    expose:
      - 5000
    environment:
      - VIRTUAL_HOST=buscar.local.me
      - LETSENCRYPT_HOST=buscar.local.me
      - VIRTUAL_PORT=5000
      - DOTNET_RUNNING_IN_CONTAINER=true
      - ASPNETCORE_ENVIRONMENT=${ENVIRONMENT}
      - ASPNETCORE_URLS=http://+:5000
    networks:
      - app_network
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5000/health
      interval: 30s
      retries: 5
      start_period: 20s
      timeout: 10s

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - html:/usr/share/nginx/html:rw
    networks:
      - app_network
    labels:
      - "com.github.nginx-proxy.nginx"
      - "nginx-proxy-redirect-to-https=true"
    depends_on:
      - api

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    restart: always
    environment:
      - ENABLE_SSL=${ENVIRONMENT}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html:rw
      - acme:/etc/acme.sh
    networks:
          - app_network

networks:
  app_network:
    driver: bridge
volumes:
  certs:
  html:
  acme:
